### PR TITLE
Add website to DESCRIPTION

### PR DESCRIPTION
**Pull request by olivroy**

### CODE REVIEW

**Comment by khufkens** [comment]
Please raise issues before a pull requests.

**Comment by khufkens** [comment]
Please introduce yourself first briefly. Why you want to make the change, and check if it doesn't create more work/stress downstream than intended. (in this case I'm not going to go through the effort of a new CRAN release for an extra URL - having these lose ends hovering over me creates more anxiety than it is worth). It is not that I don't appreciate the intention...

**Comment by olivroy** [comment]
Hi, apologies for this. the goal of adding a link to DESCRIPTION is to make it more discoverable on CRAN. A [nice blog post](https://blog.r-hub.io/2019/12/10/urls/) explains in more details. I don't think it is worth making a CRAN release for this, but it can be a nice addition when you make a CRAN release. I would not want copyright claim for this, as it is trivial. (in fact, if you want, you can add the commit yourself!)

**Comment by khufkens** [comment]
Hi @olivroy Sorry for being a bit pedantic in these matters. But clear communications help me keep track of things easier, and avoid duplicate efforts and frustrations. Say you make bigger changes I was working on as well, which would be a waste of resources. And, as I mentioned jumping the gun on things sort of implicitly puts stress on me for a release and might run afoul of some of the licensing changes I might (not sure) consider.

Anyway, best to open a line of communication first. I appreciate the reminder though, and I've pushed the changes to most repos but then I'm only accountable to myself for the releases (not to an outside contributor as well). I hope this all makes sense from my point of view.

Again, appreciate the nudges.

**Pull request closed without merging**
